# Generated by Django 4.2 on 2025-04-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='about_books',
            new_name='abt_cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='featured_books',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
