# Generated by Django 4.2 on 2025-04-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_product_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='binding',
            field=models.CharField(default='Paperback', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='page_no',
            field=models.IntegerField(default=1),
        ),
    ]
